# Generated by Django 2.0.6 on 2018-07-15 09:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180715_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 15, 9, 6, 55, 532901, tzinfo=utc)),
        ),
    ]
